### ISSUE TITLE
[refactor] Entity 수정

### ISSUE THREAD

**Issue by emilywin825** [Artview2024/Artview_BE#5]
### 📝 Description

- DB 로직 변경에 따라 Entity를 수정합니다.

---

### 📝 Todo

- [x] VisitedExhibitions Entity 삭제
- [x] MyReviews 필드 수정
- [x] MyReviewsContents Entity 추가
- [x] 연관관계에 맞게 엔티티 수정
