### ISSUE TITLE
[refactor] : 소통페이지 로그인 여부 판단 로직 추가

### ISSUE THREAD

**Issue by emilywin825** [Artview2024/Artview_BE#58]
### 📝 Description

- /api/communications/main/all/{cursor}
- /api/communications/content/{communicationsId}
- /api/communications/comment/{communicationsId}
api에서 로그인 여부에 따라 로직 분리

---

### 📝 Todo

- [ ] 위의 api는 security에서 jwt를 검증하지 않고, controller에서 검증
- [ ] 로그인을 한 유저라면, 좋아요 데이터 포함
- [ ] 로그인을 하지 않은 유저라면, 좋아요 데이터는 모두 false
